# Generated by Django 5.2.8 on 2025-12-10 02:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio')),
                ('volumen', models.IntegerField(help_text='Volumen en mililitros', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Volumen (ml)')),
                ('tipo', models.CharField(choices=[('EDT', 'Eau de Toilette'), ('EDP', 'Eau de Parfum'), ('EDC', 'Eau de Cologne'), ('PARFUM', 'Parfum'), ('SPLASH', 'Splash')], max_length=10, verbose_name='Tipo de perfume')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Unisex')], max_length=1, verbose_name='Género')),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock disponible')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='perfumes/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Perfume',
                'verbose_name_plural': 'Perfumes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
