# Generated by Django 6.0 on 2025-12-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor'), ('CAJERO', 'Cajero')], default='CAJERO', max_length=20),
        ),
    ]
