# Generated by Django 5.2.8 on 2025-12-14 16:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('marca', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('EDP', 'Eau de Parfum'), ('EDT', 'Eau de Toilette'), ('EDC', 'Eau de Cologne'), ('PARFUM', 'Parfum'), ('SPLASH', 'Body Splash')], default='EDP', max_length=10)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Unisex')], default='U', max_length=1)),
                ('notas_superiores', models.TextField(help_text='Notas de salida (ej: bergamota, limón)')),
                ('notas_medias', models.TextField(help_text='Notas de corazón (ej: jazmín, rosa)')),
                ('notas_base', models.TextField(help_text='Notas de fondo (ej: almizcle, vainilla)')),
                ('volumen', models.IntegerField(help_text='Volumen en ml', validators=[django.core.validators.MinValueValidator(1)])),
                ('concentracion', models.DecimalField(blank=True, decimal_places=2, help_text='Concentración de esencia en %', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('anio_lanzamiento', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Perfume',
                'verbose_name_plural': 'Perfumes',
                'ordering': ['marca', 'nombre'],
            },
        ),
    ]
