# Generated by Django 6.0 on 2025-12-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfume',
            name='distribuidor',
            field=models.CharField(blank=True, help_text='Distribuidor del producto', max_length=150, null=True),
        ),
    ]
