# Generated by Django 6.0 on 2025-12-11 06:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(db_index=True, help_text='Código de barras único del producto', max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='El código de barras solo puede contener números, letras y guiones', regex='^[0-9A-Za-z\\-]+$')], verbose_name='Código de Barras')),
                ('nombre', models.CharField(db_index=True, max_length=200, verbose_name='Nombre')),
                ('marca', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='Marca')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio de venta unitario', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio')),
                ('stock_actual', models.IntegerField(default=0, help_text='Cantidad actual en inventario', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(default=5, help_text='Cantidad mínima antes de alerta de reabastecimiento', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Stock Mínimo')),
                ('categoria', models.CharField(choices=[('EDT', 'Eau de Toilette'), ('EDP', 'Eau de Parfum'), ('EDC', 'Eau de Cologne'), ('PARFUM', 'Parfum'), ('SPLASH', 'Splash'), ('ACCESORIO', 'Accesorio'), ('OTRO', 'Otro')], db_index=True, max_length=20, verbose_name='Categoría')),
                ('volumen', models.IntegerField(blank=True, help_text='Volumen en mililitros', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Volumen (ml)')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('U', 'Unisex')], max_length=1, verbose_name='Género')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/', verbose_name='Imagen')),
                ('activo', models.BooleanField(default=True, help_text='Producto disponible para venta', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['codigo_barras'], name='pos_product_codigo__e57154_idx'), models.Index(fields=['nombre'], name='pos_product_nombre_0b7bca_idx'), models.Index(fields=['categoria', 'activo'], name='pos_product_categor_a0ba91_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(db_index=True, help_text='Número único de ticket generado automáticamente', max_length=20, unique=True, verbose_name='Número de Ticket')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('total', models.DecimalField(decimal_places=2, help_text='Monto total de la venta', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('MIXTO', 'Mixto')], db_index=True, max_length=20, verbose_name='Método de Pago')),
                ('estado', models.CharField(choices=[('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('PENDIENTE', 'Pendiente')], db_index=True, default='COMPLETADA', max_length=15, verbose_name='Estado')),
                ('descuento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento aplicado a la venta', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento')),
                ('notas', models.TextField(blank=True, help_text='Notas adicionales sobre la venta', verbose_name='Notas')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('motivo_cancelacion', models.TextField(blank=True, verbose_name='Motivo de Cancelación')),
                ('cajero', models.ForeignKey(help_text='Usuario que realizó la venta', on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='SaleDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad de productos vendidos', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad al momento de la venta', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Total para este producto (cantidad × precio)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Subtotal')),
                ('descuento_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento aplicado a este producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Descuento Aplicado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_detalle', to='pos.product', verbose_name='Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pos.sales', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'ordering': ['venta', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CAJERO', 'Cajero'), ('ADMINISTRADOR', 'Administrador'), ('SUPERVISOR', 'Supervisor')], default='CAJERO', help_text='Rol del usuario en el sistema POS', max_length=20, verbose_name='Rol')),
                ('turno', models.CharField(choices=[('MATUTINO', 'Matutino (8:00 - 15:00)'), ('VESPERTINO', 'Vespertino (15:00 - 22:00)'), ('NOCTURNO', 'Nocturno (22:00 - 8:00)'), ('COMPLETO', 'Tiempo Completo')], default='COMPLETO', help_text='Turno de trabajo asignado', max_length=20, verbose_name='Turno')),
                ('activo', models.BooleanField(default=True, help_text='Usuario activo en el sistema POS', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(help_text='Cantidad del movimiento (siempre positiva)', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución')], db_index=True, max_length=15, verbose_name='Tipo de Movimiento')),
                ('motivo', models.TextField(help_text='Descripción del motivo del movimiento', verbose_name='Motivo')),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha y Hora')),
                ('stock_anterior', models.IntegerField(help_text='Stock antes del movimiento', verbose_name='Stock Anterior')),
                ('stock_nuevo', models.IntegerField(help_text='Stock después del movimiento', verbose_name='Stock Nuevo')),
                ('usuario', models.ForeignKey(help_text='Usuario que registró el movimiento', on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='pos.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['-fecha'], name='pos_invento_fecha_e573b4_idx'), models.Index(fields=['producto', '-fecha'], name='pos_invento_product_55e2b5_idx'), models.Index(fields=['tipo', '-fecha'], name='pos_invento_tipo_291d47_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['-fecha_hora'], name='pos_sales_fecha_h_c9203b_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['numero_ticket'], name='pos_sales_numero__41b8e2_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['estado', '-fecha_hora'], name='pos_sales_estado_637e37_idx'),
        ),
        migrations.AddIndex(
            model_name='sales',
            index=models.Index(fields=['cajero', '-fecha_hora'], name='pos_sales_cajero__3e637c_idx'),
        ),
        migrations.AddIndex(
            model_name='saledetails',
            index=models.Index(fields=['venta'], name='pos_saledet_venta_i_309bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='saledetails',
            index=models.Index(fields=['producto'], name='pos_saledet_product_887af5_idx'),
        ),
    ]
