# Generated by Django 6.0 on 2025-12-11 06:30

from django.db import migrations
from django.utils.text import slugify


def generate_barcode(nombre, marca, pk):
    """Genera un código de barras único basado en el producto"""
    marca_code = slugify(marca)[:3].upper() if marca else 'GEN'
    nombre_code = slugify(nombre)[:5].upper()
    unique_code = f"{pk:05d}"
    return f"{marca_code}-{nombre_code}-{unique_code}"


def migrate_perfume_to_product(apps, schema_editor):
    """Migra datos de Perfume a Product"""
    Perfume = apps.get_model('rubiPerfumeria', 'Perfume')
    Product = apps.get_model('pos', 'Product')

    perfumes = Perfume.objects.all()

    for perfume in perfumes:
        codigo_barras = generate_barcode(
            perfume.nombre,
            perfume.marca,
            perfume.pk
        )

        categoria = perfume.tipo if perfume.tipo else 'OTRO'

        Product.objects.create(
            codigo_barras=codigo_barras,
            nombre=perfume.nombre,
            marca=perfume.marca,
            descripcion=perfume.descripcion,
            precio=perfume.precio,
            stock_actual=perfume.stock,
            stock_minimo=5,
            categoria=categoria,
            volumen=perfume.volumen,
            genero=perfume.genero,
            imagen=perfume.imagen,
            activo=perfume.activo,
            fecha_creacion=perfume.fecha_creacion,
            fecha_actualizacion=perfume.fecha_actualizacion,
        )


def reverse_migration(apps, schema_editor):
    """Reversa la migración"""
    Product = apps.get_model('pos', 'Product')
    Product.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('rubiPerfumeria', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            migrate_perfume_to_product,
            reverse_migration
        ),
    ]
